config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :links, except: %i(show edit update) do
    resources :hits, only: :index
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/device_detectable.rb
module DeviceDetectable
  extend ActiveSupport::Concern

  included do
    before_validation(on: :create) do
      next if user_agent.blank?

      client = DeviceDetector.new(user_agent)

      self.client_browser_name = client.name
      self.client_browser_version = client.full_version
      self.client_device_name = client.device_name
      self.client_device_type = client.device_type
      self.client_os_name = client.os_name
      self.client_os_version = client.os_full_version
    end
  end
end

app/models/concerns/locationable.rb
module Locationable
  DB_FILE = Rails.root.join('vendor', 'GeoLite2-City.mmdb').to_s.freeze

  extend ActiveSupport::Concern

  included do
    before_validation(on: :create) do
      next if remote_address.blank?

      geo = GeoIP2Compat.new(DB_FILE).lookup(remote_address)

      self.location_country_code = geo[:country_code]
      self.location_country_name = geo[:country_name]
      self.location_region_name = geo[:region_name]
      self.location_city_name = geo[:city]
    end
  end
end

app/models/concerns/pageable.rb
module Pageable
  extend ActiveSupport::Concern

  included do
    scope :paged, ->(params) do
      page_sz = params[:page_size].to_i
      page_sz = model.per_page if page_sz <= 0 || page_sz > model.max_page_sz

      page_num = params[:page_number].to_i
      page_num = 1 if page_num <= 0

      limit(page_sz).offset((page_num - 1) * page_sz).extending(PagedScope)
    end
  end

  class_methods do
    def per_page
      10
    end

    def max_page_sz
      25
    end
  end

  module PagedScope
    def page_number
      (@values[:offset] / @values[:limit]) + 1
    end

    def pages_count
      @pages_count ||= calculate_total_pages_count
    end

    def next_page?
      page_number != pages_count
    end

    def previous_page?
      page_number > 1
    end

    def next_page_number
      page_number + 1 if next_page?
    end

    def previous_page_number
      page_number - 1 if previous_page?
    end

    # Override spawn to clear instance variable caches
    def spawn #:nodoc:
      remove_instance_variable :@pages_count if instance_variable_defined? :@pages_count

      super
    end

    private

    def calculate_total_pages_count
      pages_count = limit(nil).offset(nil).count
      pages_count /= @values[:limit]
      pages_count < 1 ? 1 : pages_count
    end
  end
end

app/models/hit.rb
class Hit < ApplicationRecord
  include DeviceDetectable
  include Locationable

  belongs_to :link, counter_cache: true

  validates :remote_address, :user_agent, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  include Pageable

  belongs_to :user, counter_cache: true, optional: true

  has_many :hits

  before_validation :set_domain
  before_validation :set_ident

  validates :url, :domain, :ident, presence: true
  validates :ident, uniqueness: true
  validate :check_url_format

  after_create :update_redis_entry
  after_destroy :remove_redis_entry

  def shortened_url
    "https://#{domain}/#{ident}"
  end

  def to_param
    ident
  end

  def redis_key
    "#{Rails.application.config.redis_namespace}:#{domain}:#{ident}"
  end

  def self.next_ident
    loop do
      ident = SecureRandom.urlsafe_base64(4)

      break ident unless Link.where(ident: ident).exists?
    end
  end

  private

  def update_redis_entry
    Rails.application.redis_pool.with do |conn|
      conn.set redis_key, url
    end
  end

  def remove_redis_entry
    Rails.application.redis_pool.with do |conn|
      conn.del redis_key
    end
  end

  def check_url_format
    l_url = url.to_s.dup
    l_url.prepend 'http://' unless l_url =~ %r{\A\w+:}

    uri = URI.parse(l_url)

    errors.add :url, :invalid_protocol unless URI::HTTP === uri
    errors.add :url, :invalid_hostname unless uri.hostname.to_s.include? '.'
  end

  def set_ident
    self.ident ||= self.class.next_ident
  end

  def set_domain
    # NOTE for now we just hard code to r3xx.io
    self.domain ||= 'r3xx.io'
  end
end

app/models/miss.rb
class Miss < ApplicationRecord
  include DeviceDetectable
  include Locationable

  validates :link_ident, :domain, :remote_address, :user_agent, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :lockable, :timeoutable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder

  respond_to :html

  protected

  def page_params
    params.permit(:page_number, :page_size)
  end

  helper_method :page_params
end

app/controllers/hits_controller.rb
class HitsController < ApplicationController
  before_action :find_link!

  rescue_from ActiveRecord::RecordNotFound, with: :link_not_found

  def index
    @hits = @link.hits

    respond_with @hits
  end

  private

  def find_link!
    @link = Link.where(ident: params[:link_id]).first!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'root'

  def index
    redirect_to links_url if current_user.present?

    @link = Link.new
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  LinkNotInSession = Class.new(StandardError)

  self.responder = ApplicationResponder::CollectionResponder

  before_action :find_link_from_current_user_or_session, only: %i(edit update destroy)

  def index
    @links = user_signed_in? ? links_from_current_user : links_from_session
    @links = @links.order('created_at DESC').paged(page_params)

    if @links.empty? then redirect_to root_url
    else respond_with @links
    end
  end

  def new
    @link = Link.new

    respond_with @link
  end

  def create
    @link = create_link_from_current_user_or_session

    respond_with @link
  end

  #def update
    #@link.update(link_params)

    #respond_with @link
  #end

  # TODO remove from session is not logged
  def destroy
    @link.destroy

    respond_with @link
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end

  def links_from_current_user
    Link.where(user: current_user)
  end

  def links_from_session
    return Link.none unless session.key?(:link_idents)

    Link.where(ident: session[:link_idents])
  end

  def create_link_from_current_user_or_session
    if current_user then current_user.links.create(link_params)
    else
      Link.create(link_params).tap do |link|
        session[:link_idents] ||= []
        session[:link_idents] << link.ident
      end
    end
  end

  def find_link_from_current_user_or_session
    @link = find_link_from_current_user || find_link_from_session
  rescue ActiveRecord::RecordNotFound, LinkNotInSession
    redirect_to links_url, flash: { alert: 'Failed to find Link resource' }
  end

  def find_link_from_current_user
    current_user.links.where(ident: params[:id]).first! if current_user.present?
  end

  def find_link_from_session
    raise LinkNotInSession if session[:link_idents].blank?
    raise LinkNotInSession unless params[:id].in? session[:link_idents]

    Link.where(ident: params[:id]).first!
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  after_action :convert_session_links, on: :create

  private

  def convert_session_links
    if resource.persisted? && session.key?(:link_idents)
      session[:link_idents].each do |ident|
        link = Link.where(ident: ident).first
        link&.update(user_id: resource.id)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hits/index.html.haml
.row.align-items-center
  .w-100.clearfix
    %h2.mb-5.float-left
      Hits
      %small.text-muted= @link.shortened_url
  .w-100
    %table.table#hits-table
      %thead
        %tr
          %th{scope: 'col'} Browser
          %th{scope: 'col'} Device
          %th{scope: 'col'} Location
      %tbody
        -#- @links.each do |link|
          = render link

app/views/home/index.html.haml
.container.h-100
  .row.h-100.justify-content-center.align-items-center
    .w-100
      %div.px-2.mb-5
        %h1.display-4.text-center r3xx.io
        %h5.text-center URL Shortener and HTTP Redirect Service
      = render 'links/form', link: @link

      - if session[:link_idents].present?
        %div.text-center
          %span.mr-4
            Want to save your
            = link_to 'links', links_path, class: 'text-light'
            \?
          = link_to 'Sign up', new_user_registration_path, class: 'btn btn-light btn-large'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title r3xx.io | HTTP Redirect Service

    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}

    = csrf_meta_tags

    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Fira+Mono'
    = stylesheet_link_tag 'application', media: 'all', integrity: true
    = javascript_include_tag 'application', integrity: true
  %body
    %nav.navbar.navbar-expand-md.navbar-dark.bg-primary
      .container
        = link_to 'r3xx.io', root_path, class: 'navbar-brand'

        %button.navbar-toggler{data: { toggle: 'collapse', target: '#navbarSupportedContent' }}
          %span.navbar-toggler-icon

        .collapse.navbar-collapse.justify-content-end#navbarSupportedContent
          %ul.navbar-nav.text-right
            %li.nav-item{class: current_page?(controller: '/links') ? 'active' : nil}
              = link_to 'Links', links_path, class: 'nav-link'
            - unless user_signed_in?
              %li.nav-item
                = link_to 'Login', new_user_session_path, class: 'nav-link'

    .container.mt-5
      = yield

    = javascript_include_tag 'footer'

app/views/layouts/root.html.haml
!!!
%html
  %head
    %title r3xx.io | HTTP Redirect Service

    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no'}

    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Fira+Mono'
    = stylesheet_link_tag 'application', media: 'all', integrity: true
    = javascript_include_tag 'application', integrity: true
  %body.root
    = yield

app/views/links/_form.haml
= bootstrap_form_for link, class: 'col-12 mx-auto', style: 'max-width: 80%' do |f|
  = f.text_field :url, hide_label: true, placeholder: 'Enter a valid url'

  .form-group
    - if current_page?(controller: '/home', action: 'index')
      %button.btn.btn-light.btn-lg.btn-block Create
    - else
      %button.btn.btn-primary.btn-lg.btn-block
        = link.new_record? ? 'Create' : 'Update'

app/views/links/_link.haml
%tr
  %td
    = link_to link.url, target: '_new' do
      = link.url
      %i.fas.fa-external-link-alt
    -#.float-right
      %a{href: link.shortened_url} #{link.ident}

  %td
    - if user_signed_in?
      = link_to number_with_delimiter(link.hits_count), link_hits_path(link)
    - else
      = number_with_delimiter(link.hits_count)
  %td= l link.created_at.to_date, format: :short
  %td
    %button.btn.btn-primary.btn-link.text-primary.copy-btn{data: {'clipboard-text': link.shortened_url}}
      %i.fas.fa-copy
      %span Copy Clipboard
    = link_to link_path(link), method: :delete, 'data-confirm': 'Are you sure?', class: 'btn btn-link btn-danger text-danger' do
      %i.fas.fa-trash-alt
      %span Delete

app/views/links/index.html.haml
.row.align-items-center
  .w-100.clearfix
    %h2.mb-5.float-left
      Links
      = link_to 'New Link', new_link_path, class: 'btn btn-link btn-inline btn-success'

    - unless user_signed_in?
      .alert.alert-info.float-right
        = link_to 'Create', new_user_registration_path, class: 'alert-link'
        an account to save your links
  .w-100
    %table.table#links-table
      %thead
        %tr
          %th{scope: 'col'} Link
          %th{scope: 'col'} Hits
          %th{scope: 'col'} Created
          %th{scope: 'col'} Actions
      %tbody
        - @links.each do |link|
          = render link

    = render 'shared/pagination_links', scope: @links

app/views/links/new.html.haml
.row.align-items-center
  .w-100
    %h2.mb-5 Create new Link
  .w-100
    = render 'links/form', link: @link

app/views/shared/_pagination_links.html.haml
- base_params = page_params.slice(:page_size)

%nav{'aria-label' => "Pagination navigation"}
  %ul.pagination.justify-content-center
    - if scope.previous_page?
      %li.page-item
        = link_to links_path(base_params.merge(page_number: scope.previous_page_number)), class: 'page-link' do
          %i.fas.fa-angle-double-left{'aria-hidden': 'true'}
          Previous
    - else
      %li.page-item.disabled
        .page-link
          %i.fas.fa-angle-double-left{'aria-hidden': 'true'}
          Previous

    %li.page-item.disabled
      .page-link
        = "#{scope.page_number} of #{scope.pages_count}"

    - if scope.next_page?
      %li.page-item
        = link_to links_path(base_params.merge(page_number: scope.next_page_number)), class: 'page-link' do
          Next
          %i.fas.fa-angle-double-right{'aria-hidden': 'true'}
    - else
      %li.page-item.disabled
        .page-link
          Next
          %i.fas.fa-angle-double-right{'aria-hidden': 'true'}